const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision
	];
};
self.C3_JsPropNameTable = [
	{Menu_fundo: 0},
	{Jogo_Fundo: 0},
	{Jogo_Chao: 0},
	{Jogo_Player: 0},
	{Jogo_Arvore: 0},
	{Teclado: 0},
	{Fixar: 0},
	{Jogo_Hitboxplayer: 0},
	{txtdebug: 0},
	{Tutorial_janelatutorial: 0},
	{Tutorial_btn_cont: 0},
	{Tutorial_btn_voltar: 0},
	{Toque: 0},
	{Mouse: 0},
	{Logo: 0},
	{btn_jogar: 0},
	{btn_creditos: 0},
	{btn_sair: 0},
	{Creditos_btn_voltar: 0},
	{Jogo_hud_Arvorescortadas: 0},
	{arvore: 0},
	{relogiuo: 0},
	{Jogo_hud_temporestante: 0},
	{Jogo_hud_Contagem: 0},
	{Jogo_hud_tempoencerrado: 0},
	{Jogo_hud_final_arvorescortadas: 0},
	{arvore2: 0},
	{Navegador: 0},
	{Jogo_hud_coisania: 0},
	{Sprite: 0},
	{Jogo_final_btn: 0},
	{Jogo_final_sim: 0},
	{Jogo_final_nao: 0},
	{degrade: 0},
	{creditps: 0},
	{creditps2: 0},
	{Creditos_fundo: 0},
	{VidaArvore: 0},
	{ArvoresCortadas: 0},
	{Cronometro: 0},
	{Contagem: 0}
];

self.InstanceType = {
	Menu_fundo: class extends self.ISpriteInstance {},
	Jogo_Fundo: class extends self.ISpriteInstance {},
	Jogo_Chao: class extends self.ISpriteInstance {},
	Jogo_Player: class extends self.ISpriteInstance {},
	Jogo_Arvore: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Jogo_Hitboxplayer: class extends self.ISpriteInstance {},
	txtdebug: class extends self.ITextInstance {},
	Tutorial_janelatutorial: class extends self.ISpriteInstance {},
	Tutorial_btn_cont: class extends self.ISpriteInstance {},
	Tutorial_btn_voltar: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Logo: class extends self.ISpriteInstance {},
	btn_jogar: class extends self.ISpriteInstance {},
	btn_creditos: class extends self.ISpriteInstance {},
	btn_sair: class extends self.ISpriteInstance {},
	Creditos_btn_voltar: class extends self.ISpriteInstance {},
	Jogo_hud_Arvorescortadas: class extends self.ITextInstance {},
	arvore: class extends self.ISpriteInstance {},
	relogiuo: class extends self.ISpriteInstance {},
	Jogo_hud_temporestante: class extends self.ITextInstance {},
	Jogo_hud_Contagem: class extends self.ITextInstance {},
	Jogo_hud_tempoencerrado: class extends self.ISpriteInstance {},
	Jogo_hud_final_arvorescortadas: class extends self.ITextInstance {},
	arvore2: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	Jogo_hud_coisania: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Jogo_final_btn: class extends self.ISpriteInstance {},
	Jogo_final_sim: class extends self.ITextInstance {},
	Jogo_final_nao: class extends self.ITextInstance {},
	degrade: class extends self.ISpriteInstance {},
	creditps: class extends self.ISpriteInstance {},
	creditps2: class extends self.ISpriteInstance {},
	Creditos_fundo: class extends self.ISpriteInstance {}
}